"""Unit tests for `pulse graduate` — no network, operates on bundled XML files."""

from __future__ import annotations

import ast

from typer.testing import CliRunner

from pulse.cli import app

runner = CliRunner()


def test_graduate_produces_syntactically_valid_python(tmp_path):
    out = tmp_path / "fetch_generated.py"
    result = runner.invoke(app, ["graduate", "drug-deaths-by-year-2018-2024-req.xml", "-o", str(out)])
    assert result.exit_code == 0
    assert out.exists()
    ast.parse(out.read_text())  # raises SyntaxError if malformed


def test_graduate_docstring_closes_properly(tmp_path):
    out = tmp_path / "fetch_generated.py"
    runner.invoke(app, ["graduate", "drug-deaths-by-year-2018-2024-req.xml", "-o", str(out)])
    tree = ast.parse(out.read_text())
    docstring = ast.get_docstring(tree)
    assert docstring is not None
    assert "Generated by `pulse graduate`" in docstring


def test_graduate_project_root_points_at_health_repo_root(tmp_path):
    out = tmp_path / "fetch_generated.py"
    runner.invoke(app, ["graduate", "drug-deaths-by-year-2018-2024-req.xml", "-o", str(out)])
    text = out.read_text()
    # This script is meant to live at src/wonder/queries/<file>.py inside the
    # health repo — parents[3] from there is the repo root (queries -> wonder
    # -> src -> repo root). parents[2] would land one level too shallow.
    assert "parents[3]" in text


def test_graduate_uses_header_array_pairing_not_dicts(tmp_path):
    out = tmp_path / "fetch_generated.py"
    runner.invoke(app, ["graduate", "drug-deaths-by-year-2018-2024-req.xml", "-o", str(out)])
    text = out.read_text()
    assert "get_column_headers" in text
    assert "parse_response_to_arrays" in text
    assert "parse_response_to_dicts" not in text


def test_graduate_embeds_correct_dataset_id(tmp_path):
    out = tmp_path / "fetch_generated.py"
    runner.invoke(app, ["graduate", "drug-deaths-by-year-2018-2024-req.xml", "-o", str(out)])
    assert 'DATASET_ID = "D176"' in out.read_text()


def test_graduate_missing_file_exits_nonzero():
    result = runner.invoke(app, ["graduate", "not-a-real-file.xml"])
    assert result.exit_code != 0


def test_graduate_no_output_flag_prints_to_stdout():
    result = runner.invoke(app, ["graduate", "drug-deaths-by-year-2018-2024-req.xml"])
    assert result.exit_code == 0
    assert "def main()" in result.stdout
